### ISSUE TITLE
Allow for faucet credentials to be provided in external config file

### ISSUE THREAD

**Issue by thunderbiscuit** [mbcse/tatoonie_discord_script#1]
I'm not sure typically what type of file is used for Rust but maybe toml format.

We'd need to be able to provide faucet url and webhook as a configuration which the script can use. This will also make the script more customizable and reusable for other folks!

**Comment by mbcse** [comment]
@thunderbiscuit  I have added Support for toml based config file

**Comment by thunderbiscuit** [comment]
Great! That's good stuff.
